version: "3.8"

services:
  userservice:
    image: userservice
    build:
      context: ./userservice
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
  
  bookservice:
    image: bookservice
    build:
      context: ./bookservice
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"